import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// --- THEME CONSTANTS ---
const ORANGE_MAIN = [249, 115, 22]; // Orange 500
const ORANGE_LIGHT = [255, 237, 213]; // Orange 100
const SLATE_900 = [15, 23, 42];
const SLATE_500 = [100, 116, 139];
const SLATE_200 = [226, 232, 240];
const EMERALD = [16, 185, 129];
const ROSE = [244, 63, 94];

const addHeader = (doc, width, title, subTitle) => {
    // Top Bar
    doc.setFillColor(...ORANGE_MAIN);
    doc.rect(0, 0, width, 6, 'F');

    // Branding
    doc.setFontSize(24);
    doc.setTextColor(...SLATE_900);
    doc.setFont('helvetica', 'bold');
    doc.text("Srot Finance", 20, 25);

    // Title
    doc.setFontSize(16);
    doc.setTextColor(...SLATE_500);
    doc.setFont('helvetica', 'normal');
    doc.text(title, width - 20, 25, { align: 'right' });

    if (subTitle) {
        doc.setFontSize(10);
        doc.text(subTitle, width - 20, 31, { align: 'right' });
    }

    // Divider
    doc.setDrawColor(...SLATE_200);
    doc.setLineWidth(0.5);
    doc.line(20, 36, width - 20, 36);
};

const addFooter = (doc, width, height) => {
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(...SLATE_500);
        doc.text('Generated by Srot Finance • Secure Financial Tracking • fin.swinfosystems.online', width / 2, height - 10, { align: 'center' });
        doc.text(`Page ${i} of ${pageCount}`, width - 20, height - 10, { align: 'right' });
    }
};

export const createPDF = (transactions, stats, userProfile, filterLabel) => {
    const doc = new jsPDF();
    const width = doc.internal.pageSize.width;
    const height = doc.internal.pageSize.height;

    addHeader(doc, width, "Financial Intelligence Report", `Period: ${filterLabel}`);

    // User Info
    doc.setFontSize(10);
    doc.setTextColor(...SLATE_900);
    doc.text(`User: ${userProfile?.user_metadata?.full_name || 'Valued User'}`, 20, 48);
    doc.setTextColor(...SLATE_500);
    doc.text(`Date Generated: ${new Date().toLocaleDateString()}`, 20, 53);

    // Summary Cards Section
    let yPos = 65;
    const cardGap = 10;
    const cardWidth = (width - 40 - (cardGap * 2)) / 3;
    const cardHeight = 28;

    const drawSummaryCard = (x, label, value, color) => {
        doc.setDrawColor(230, 230, 230);
        doc.setFillColor(252, 252, 252);
        doc.roundedRect(x, yPos, cardWidth, cardHeight, 3, 3, 'FD');

        // Color Strip
        doc.setFillColor(...color);
        doc.rect(x, yPos + 4, 1.5, cardHeight - 8, 'F');

        doc.setFontSize(9);
        doc.setTextColor(...SLATE_500);
        doc.setFont('helvetica', 'bold');
        doc.text(label.toUpperCase(), x + 8, yPos + 10);

        doc.setFontSize(14);
        doc.setTextColor(...SLATE_900);
        doc.text(`Rs. ${value.toLocaleString()}`, x + 8, yPos + 21);
    };

    drawSummaryCard(20, 'Total Income', stats.income, EMERALD);
    drawSummaryCard(20 + cardWidth + cardGap, 'Total Expense', stats.expense, ROSE);
    drawSummaryCard(20 + (cardWidth + cardGap) * 2, 'Net Savings', stats.balance, ORANGE_MAIN);

    // Transactions Table
    yPos += 45;

    doc.setFontSize(12);
    doc.setTextColor(...SLATE_900);
    doc.setFont('helvetica', 'bold');
    doc.text("Transaction History", 20, yPos);
    yPos += 5;

    const tableData = transactions.map(t => [
        new Date(t.date).toLocaleDateString(),
        t.title,
        t.category,
        t.type.toUpperCase(),
        `Rs. ${t.amount.toLocaleString()}`
    ]);

    autoTable(doc, {
        startY: yPos,
        head: [['Date', 'Description', 'Category', 'Type', 'Amount']],
        body: tableData,
        theme: 'plain',
        styles: { fontSize: 9, cellPadding: 3, textColor: SLATE_500 },
        headStyles: { fillColor: [248, 250, 252], textColor: SLATE_900, fontStyle: 'bold', minCellHeight: 12, valign: 'middle' },
        columnStyles: {
            0: { cellWidth: 25 },
            1: { cellWidth: 'auto' },
            3: { cellWidth: 25, halign: 'center', fontStyle: 'bold' },
            4: { halign: 'right', fontStyle: 'bold', cellWidth: 35 }
        },
        alternateRowStyles: { fillColor: [255, 255, 255] },
        didParseCell: function (data) {
            if (data.section === 'body') {
                if (data.column.index === 3) {
                    data.cell.styles.textColor = data.cell.raw === 'INCOME' ? EMERALD : ROSE;
                }
            }
        },
        didDrawCell: (data) => {
            if (data.section === 'body' && data.column.index === data.table.columns.length - 1) {
                doc.setDrawColor(240, 240, 240);
                doc.line(data.table.settings.margin.left, data.cell.y + data.cell.height, width - data.table.settings.margin.right, data.cell.y + data.cell.height);
            }
        }
    });

    addFooter(doc, width, height);
    return doc;
};

export const getPDFFile = (transactions, stats, userProfile, filterLabel) => {
    const doc = createPDF(transactions, stats, userProfile, filterLabel);
    const blob = doc.output('blob');
    return new File([blob], `Fin_Report_${Date.now()}.pdf`, { type: 'application/pdf' });
};

// --- SCHEME TAX INFO FOR PDF ---
const SCHEME_TAX_DATA = {
    SIP: {
        fullName: 'Systematic Investment Plan (SIP)',
        section: 'Equity Mutual Fund — Capital Gains',
        taxRules: [
            ['Holding Period for LTCG', '> 12 months per SIP unit'],
            ['LTCG Tax Rate', '12.5% on gains exceeding Rs.1,25,000/year'],
            ['STCG Tax Rate', '20% if redeemed within 12 months'],
            ['Indexation', 'Not available for equity MFs'],
            ['TDS', 'Not applicable on equity MFs'],
        ],
        exemptions: [
            'LTCG up to Rs.1,25,000 per FY is fully exempt from tax',
            'Each SIP installment treated as a separate purchase',
            'No TDS deducted on equity mutual fund redemptions',
            'Dividend income taxable at investor slab rate',
        ],
    },
    Lumpsum: {
        fullName: 'Lumpsum Investment',
        section: 'Equity MF — One-time Capital Gains',
        taxRules: [
            ['LTCG Qualification', 'Holding > 12 months'],
            ['LTCG Tax', '12.5% on gains > Rs.1.25L'],
            ['STCG Tax', '20%'],
            ['Indexation', 'Not available'],
            ['Surcharge', 'Based on total annual income'],
        ],
        exemptions: [
            'First Rs.1,25,000 LTCG per FY is tax-free',
            'No Sec 80C deduction for equity MF',
            'Debt MFs (post Apr 2023): gains taxed at slab rate',
        ],
    },
    'Fixed Deposit': {
        fullName: 'Fixed Deposit (FD)',
        section: 'Income from Other Sources',
        taxRules: [
            ['Interest Tax', 'Fully taxable at slab rate'],
            ['TDS Threshold (<60 yrs)', 'Rs.50,000/year'],
            ['TDS Threshold (60+ yrs)', 'Rs.1,00,000/year'],
            ['TDS Rate (PAN)', '10%'],
            ['TDS Rate (No PAN)', '20%'],
        ],
        exemptions: [
            '5-Year Tax Saver FD: Sec 80C deduction up to Rs.1.5L (Old Regime)',
            'Senior citizens: Rs.50,000 exempt under Sec 80TTB',
            'Form 15G/15H to avoid TDS if income below taxable limit',
        ],
    },
    PPF: {
        fullName: 'Public Provident Fund (PPF)',
        section: 'EEE — Exempt-Exempt-Exempt',
        taxRules: [
            ['Contribution Deduction', 'Sec 80C up to Rs.1.5L/year'],
            ['Interest Earned', '100% Tax Free'],
            ['Maturity Amount', '100% Tax Free'],
            ['Current Rate', '7.1% p.a. compounded yearly'],
            ['Lock-in', '15 years (partial from Yr 7)'],
        ],
        exemptions: [
            'PPF enjoys EEE status — zero tax at all stages',
            'Interest exempt under Section 10(11)',
            'Max annual investment: Rs.1,50,000',
            'Available in Old & New tax regimes',
        ],
    },
    Interest: {
        fullName: 'Simple Interest Calculator',
        section: 'Income from Other Sources',
        taxRules: [
            ['Interest Tax', 'Taxed at income slab rate'],
            ['Sec 80TTA (Savings)', 'Rs.10,000 exempt (<60 yrs)'],
            ['Sec 80TTB (Senior)', 'Rs.50,000 exempt (60+ yrs)'],
            ['TDS', 'Based on source of interest'],
        ],
        exemptions: [
            'Savings interest up to Rs.10K exempt (80TTA)',
            'Senior citizens: Rs.50K interest exempt (80TTB)',
            'PPF, Sukanya Samriddhi interest fully exempt',
        ],
    },
};

export const getCalcPDFFile = (title, data, result, userProfile) => {
    const doc = new jsPDF();
    const width = doc.internal.pageSize.width;
    const height = doc.internal.pageSize.height;

    // Stylish Sidebar
    doc.setFillColor(...ORANGE_MAIN);
    doc.rect(0, 0, 15, height, 'F');

    // Header
    doc.setFontSize(28);
    doc.setTextColor(...SLATE_900);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 35, 30);

    doc.setFontSize(12);
    doc.setTextColor(...ORANGE_MAIN);
    doc.text("ANALYSIS & PROJECTION REPORT", 35, 38);

    // Fiscal Year badge
    doc.setFontSize(9);
    doc.setTextColor(255, 255, 255);
    doc.setFillColor(...SLATE_900);
    doc.roundedRect(width - 55, 20, 38, 14, 3, 3, 'F');
    doc.text('FY 2025-26', width - 52, 29);

    // Meta Info
    doc.setFontSize(10);
    doc.setTextColor(...SLATE_500);
    doc.setFont('helvetica', 'normal');
    doc.text(`Prepared for: ${userProfile?.user_metadata?.full_name || 'Valued Client'}`, 35, 50);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 35, 56);

    doc.setDrawColor(...SLATE_200);
    doc.line(35, 62, width - 20, 62);

    // Inputs Section
    let yPos = 75;
    doc.setFontSize(14);
    doc.setTextColor(...SLATE_900);
    doc.setFont('helvetica', 'bold');
    doc.text("Input Parameters", 35, yPos);

    yPos += 10;
    const inputs = [
        ['Investment Amount', `Rs. ${parseFloat(data.amount).toLocaleString()}`],
        ['Duration', `${data.duration} Years`],
        ['Interest / Return Rate', `${data.rate || '7.1'}%`],
        ['Expense Ratio', `${data.expense_ratio || '0'}%`]
    ];

    doc.setFontSize(11);
    inputs.forEach(([label, val], i) => {
        if (i % 2 === 0 && i !== 0) yPos += 12;
        const xOffset = i % 2 === 0 ? 35 : 120;

        doc.setTextColor(...SLATE_500);
        doc.setFont('helvetica', 'normal');
        doc.text(label, xOffset, yPos);

        doc.setTextColor(...SLATE_900);
        doc.setFont('helvetica', 'bold');
        doc.text(val, xOffset, yPos + 6);
    });

    // Results Box
    yPos += 25;
    doc.setFillColor(...ORANGE_LIGHT);
    doc.setDrawColor(...ORANGE_MAIN);
    doc.roundedRect(30, yPos, width - 50, 55, 4, 4, 'FD');

    const resYStart = yPos + 14;

    // Invested
    doc.setFontSize(10);
    doc.setTextColor(...SLATE_500);
    doc.text("Total Invested", 45, resYStart);
    doc.setFontSize(14);
    doc.setTextColor(...SLATE_900);
    doc.text(`Rs. ${Math.round(result.invested).toLocaleString()}`, 45, resYStart + 8);

    // Returns
    doc.setFontSize(10);
    doc.setTextColor(...SLATE_500);
    doc.text("Total Gains", 100, resYStart);
    doc.setFontSize(14);
    doc.setTextColor(...EMERALD);
    doc.text(`+ Rs. ${Math.round(result.returns).toLocaleString()}`, 100, resYStart + 8);

    // Final
    doc.setFontSize(12);
    doc.setTextColor(...ORANGE_MAIN);
    doc.setFont('helvetica', 'bold');
    doc.text("MATURITY VALUE", width - 80, resYStart);
    doc.setFontSize(22);
    doc.text(`Rs. ${Math.round(result.netTotal).toLocaleString()}`, width - 80, resYStart + 12);

    // Tax estimation
    doc.setFontSize(9);
    doc.setTextColor(...ROSE);
    doc.text(`Estimated Tax: Rs. ${Math.round(result.tax).toLocaleString()}`, 45, resYStart + 28);

    // --- TAX & SCHEME INFO SECTION ---
    yPos += 70;
    const schemeInfo = SCHEME_TAX_DATA[title] || null;

    if (schemeInfo) {
        doc.setFontSize(13);
        doc.setTextColor(...SLATE_900);
        doc.setFont('helvetica', 'bold');
        doc.text(`Tax Treatment — ${schemeInfo.fullName}`, 35, yPos);
        doc.setFontSize(9);
        doc.setTextColor(...ORANGE_MAIN);
        doc.text(`Section: ${schemeInfo.section} | As per Indian IT Act, FY 2025-26`, 35, yPos + 7);

        // Tax Rules Table
        yPos += 12;
        autoTable(doc, {
            startY: yPos,
            margin: { left: 35, right: 20 },
            head: [['Rule', 'Details']],
            body: schemeInfo.taxRules,
            theme: 'striped',
            headStyles: { fillColor: SLATE_900, textColor: 255, fontSize: 9 },
            styles: { fontSize: 9, cellPadding: 3 },
            alternateRowStyles: { fillColor: [248, 250, 252] },
            columnStyles: { 0: { fontStyle: 'bold', cellWidth: 55 } }
        });

        // Exemptions
        yPos = (doc.lastAutoTable?.finalY || yPos + 60) + 10;

        // Check if we need a new page
        if (yPos > height - 80) {
            doc.addPage();
            yPos = 30;
        }

        doc.setFontSize(11);
        doc.setTextColor(...EMERALD);
        doc.setFont('helvetica', 'bold');
        doc.text("Tax Benefits & Exemptions", 35, yPos);
        yPos += 6;

        doc.setFontSize(9);
        doc.setTextColor(...SLATE_500);
        doc.setFont('helvetica', 'normal');
        schemeInfo.exemptions.forEach((ex, i) => {
            if (yPos > height - 40) {
                doc.addPage();
                yPos = 30;
            }
            doc.text(`✓ ${ex}`, 38, yPos);
            yPos += 6;
        });
    }

    // Projections Table if available
    if (result.projections && result.projections.length > 0) {
        yPos += 10;
        if (yPos > height - 60) {
            doc.addPage();
            yPos = 30;
        }

        doc.setFontSize(14);
        doc.setTextColor(...SLATE_900);
        doc.setFont('helvetica', 'bold');
        doc.text("Growth Projection (Yearly)", 35, yPos);

        const projData = result.projections.map(p => [
            `Year ${p.year}`,
            `Rs. ${Math.round(p.invested).toLocaleString()}`,
            `Rs. ${Math.round(p.total).toLocaleString()}`,
            `+${p.invested > 0 ? (((p.total - p.invested) / p.invested) * 100).toFixed(1) : '0'}%`
        ]);

        autoTable(doc, {
            startY: yPos + 5,
            margin: { left: 35 },
            head: [['Period', 'Invested', 'Projected Value', 'Growth']],
            body: projData,
            theme: 'striped',
            headStyles: { fillColor: SLATE_900, textColor: 255 },
            styles: { fontSize: 10, cellPadding: 3 },
            alternateRowStyles: { fillColor: [248, 250, 252] },
            columnStyles: {
                3: { textColor: EMERALD, fontStyle: 'bold' }
            }
        });
    }

    // Disclaimer
    const disclaimerY = doc.internal.pageSize.height - 35;
    doc.setFontSize(8);
    doc.setTextColor(...SLATE_500);
    doc.setFont('helvetica', 'italic');
    doc.text("* Tax calculations based on FY 2025-26 Indian Income Tax rules. Actual tax may vary based on total income,", 35, disclaimerY);
    doc.text("  applicable surcharge, and cess. This is informational only, not financial/tax advice.", 35, disclaimerY + 5);

    addFooter(doc, width, height);

    const blob = doc.output('blob');
    return new File([blob], `${title.replace(/\s+/g, '_')}_SrotFin.pdf`, { type: 'application/pdf' });
};
